// <auto-generated />
namespace Translations.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Quiz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quiz));
        
        string IMigrationMetadata.Id
        {
            get { return "201711180803172_Quiz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
